export const historyListMockData = [
	{ id: 1, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 2, talkTitle: 'title2' },
    { id: 3, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 4, talkTitle: 'title2' },
    { id: 5, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 6, talkTitle: 'title2' },
    { id: 7, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 8, talkTitle: 'title2' },
    { id: 9, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 10, talkTitle: 'title2' },
    { id: 11, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 12, talkTitle: 'title2' },
    { id: 13, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 14, talkTitle: 'title2' },
    { id: 15, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 16, talkTitle: 'title2' },
    { id: 17, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 18, talkTitle: 'title2' },
    { id: 19, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 20, talkTitle: 'title2' },
    { id: 21, talkTitle: 'title1hdsgfoabfgwbcgtrkjavfyhabfhsnfgsbfuabfyuriosbf' },
	{ id: 22, talkTitle: 'title2' }
]
